version: 2

sources:
  - name: 'C3_SHARED'
    #database: 'CR_C3PROD_VIEWS'
    database: 'JAFFLE'
    schema: 'PUBLIC'
    tables:
      - name: 'DS_IID_DELETES_DO_NOT_SELL'
        description: Snowflake Share containing DS_IID values to scrub out for Compliance 

  - name: 'M1EE'
    #database: 'CLIENT_AMEX'
    database: 'JAFFLE'
    tables:
      - name: 'M1_DSIID_CMID_DS'
        description: Snowflake Share of M1/DS_IID Crosswalk that supports translation of AMEX Encrypted CMID
      
  - name: 'SHARED'
    #database: 'CLIENT_AMEX'
    database: 'JAFFLE'
    tables:
      - name: 'B2B'
        description: Snowflake Share of B2B Build source data

  - name: 'DKB_ASSETS'
    #database: 'CR_AMEX_CROSSWALK_SHARE'
    database: 'JAFFLE'
    tables:
      - name: 'DKB_003_XWALK_COMPOSITE'
        description: Snowflake Share of Composite Crosswalk
