version: 2

sources:
  - name: 'C3_SHARED'
    #database: 'CR_C3PROD_VIEWS'
    database: 'JAFFLE'
    schema: 'PUBLIC'
    tables:
      - name: 'DS_IID_DELETES_DO_NOT_SELL'

  - name: 'M1EE'
    #database: 'CLIENT_AMEX'
    database: 'JAFFLE'
    tables:
      - name: 'M1_DSIID_CMID_DS'


